### ISSUE TITLE
Unable to load locale resources

### ISSUE THREAD

**Issue by arashi01** [shuwariafrica/chromisery#61]
Attempting to run the application results in the following error loading locale bundles.

```
~/Projects/chromisery-sbt git:[main]

sbt:Chromisery> chromisery-pos/run
[info] running (fork) uk.chromis.pos.forms.StartPOS 
[info] Fx : 21.0.5+1
[error] Dec 22, 2024 3:26:08 AM uk.chromis.pos.forms.AppConfig <init>
[error] INFO: Reading configuration file: /home/arashi01/chromispos.properties
[info] Fx : 21.0.5+1
[error] Dec 22, 2024 3:26:08 AM uk.chromis.data.loader.PreparedSentence openExec
[error] INFO: Executing prepared SQL: SELECT VERSION FROM APPLICATIONS WHERE ID = ?
[error] Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
[error]         at uk.chromis.pos.forms.JRootApp.initComponents(JRootApp.java:818)
[error]         at uk.chromis.pos.forms.JRootApp.<init>(JRootApp.java:168)
[error]         at uk.chromis.pos.forms.JRootFrame.initFrame(JRootFrame.java:62)
[error]         at uk.chromis.pos.forms.StartPOS$1.run(StartPOS.java:220)
[error]         at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
[error]         at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[error]         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[error]         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[error]         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[error]         at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[error]         at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[error] Caused by: java.util.MissingResourceException: Can't find bundle for base name pos_messages, locale en_GB
[error]         at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2059)
[error]         at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1697)
[error]         at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1600)
[error]         at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1555)
[error]         at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:861)
[error]         at uk.chromis.beans.LocaleResources.addBundleName(LocaleResources.java:51)
[error]         at uk.chromis.pos.forms.AppLocal.<clinit>(AppLocal.java:41)
[error]         ... 17 more

```

**Comment by arashi01** [comment]
Related to #9
